### ISSUE TITLE
Concede solo payer game

### ISSUE THREAD

**Issue by aloisdg** [terraforming-mars/terraforming-mars#5428] opened 2023-02-24 15:37 UTC
Hello,

While we are talking about [purging timeframe](https://github.com/terraforming-mars/terraforming-mars/issues/5362), I would like to allow people to [resign](https://github.com/terraforming-mars/terraforming-mars/issues/93) in solo mode. A resigned game in solo purge automatically. I often leave game mid-game when I know that I will never surpass my best score.

"Resign game" should be a standard action spawning a confirmation modal.

![image](https://user-images.githubusercontent.com/3449303/221218466-f955eeb3-6fe0-45c1-ad06-618fa7409300.png)

WDYT?

**Comment by kberg** [comment] 2023-02-24 15:39
Solo games can be resigned by just not finishing them. This was discussed on the Discord a few years ago, and it's not worth the effort.

**Comment by kberg** [comment] 2023-02-24 15:40
As mentioned, this is a duplicate of #93.

**Comment by aloisdg** [comment] 2023-02-24 15:40
Yes but we are still waiting 24h to remove them.

**Comment by kberg** [comment] 2023-02-24 15:42
What problem is that causing?

**Comment by aloisdg** [comment] 2023-02-24 15:42
@kberg I already mentioned #93 in this issue. This is different here because the goal is not only to ignore the game, but to actively ask to be purged

**Comment by kberg** [comment] 2023-02-24 15:43
Right. Besides that, what difference does that actually make? Why is that better than what currently happens?

**Comment by aloisdg** [comment] 2023-02-24 15:45
Nothing more. I am just sad to have some games waiting to be purged in the common shared disk while I know that they are superfluous.

**Comment by kberg** [comment] 2023-02-24 16:00
Oh, yeah. Well, thank you. That hasn't been much of a reason for wasted disk space, but thank you for thinking about it!

**Closed** 2023-02-24 16:00 UTC
Labels: duplicate, enhancement
