### ISSUE TITLE
new regression: card resources are now missing from *played* cards section

### ISSUE THREAD

**Issue by kevinb9n** [terraforming-mars/terraforming-mars#2716] opened 2021-02-09 15:50 UTC
They did return to the places they had been missing from for the last few days, BUT,

<img width=500 src=https://user-images.githubusercontent.com/934551/107389260-7df39780-6aab-11eb-9c07-8903819bfbed.png>

**Comment by kberg** [comment] 2021-02-09 16:08
Whomever fixes this, please provide a unit test.

Unit tests on the UI are tricky, mostly because we haven't done a lot of
them yet, but I will be happy to help you.

>

**Comment by sienmich** [comment] 2021-02-09 16:33
Fixed in https://github.com/bafolts/terraforming-mars/pull/2714
No test at the moment, sorry.
I can add them later

**Comment by kberg** [comment] 2021-02-09 16:44
Seinmich, I've been reducing time on this project (been playing a solo
campaign of Scythe in the evening. Very rewarding.)

But I can focus on this with you. Let's take it off-list.

**Comment by bafolts** [comment] 2021-02-10 01:05
Couldn't agree more about unit tests here. Especially during bugs which we know are regressions. Great opportunity for regression test. We do need to write more so that they eventually become as easy to write as the server side unit tests.

**Comment by kevinb9n** [comment] 2021-02-23 18:02
Is it okay to close this bug now?

**Comment by sienmich** [comment] 2021-02-23 22:02
> Is it okay to close this bug now?

After the tests. I'll add them eventually, just have to do some other things currently

**Closed** 2022-04-19 18:55 UTC
