### ISSUE TITLE
Deuterium Export not presented as actionable

### ISSUE THREAD

**Issue by MEGALEF** [terraforming-mars/terraforming-mars#6047] opened 2023-09-27 09:06 UTC
1. Added a resource to Deuterium Export using Corroder suits. Now Deuterium Export won’t show up as an actionable card (not even to add a resource). The log shows a floater being added to Deuterium Exports and the card displays it.

2. Play Deuterium Export. Play Corroder Suits to add a resource to Deuterium Export. Expected: Deuterium Export should be actionable to remove a floater and raise power prod.

3. 
4. {
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s4a612c62cee6",
  "color": "blue",
  "step": 5,
  "version": "7b6cc3d",
  "builtAt": "Wed, 27 Sep 2023 05:35:32 GMT",
  "browser": "Safari 15",
  "language": "en",
  "experimental_ui": false
}

**Comment by MEGALEF** [comment] 2023-09-27 09:09
Same issue as #6043

**Comment by kberg** [comment] 2023-09-27 17:43
Closing as duplicate of #6043, as you see. (A fix is on its way out.)

**Closed by kberg** 2023-09-27 17:43 UTC
