### ISSUE TITLE
deadlock: empty deck + empty graveyard + draw card

### ISSUE THREAD

**Issue by TomaszKozera** [terraforming-mars/terraforming-mars#4179] opened 2022-03-03 15:23 UTC
So not something that will happen often but I got into a case where the play deck was empty, there were no cards in graveyard and I played the Mangrove card on a tile that makes you draw a card. I played it on the ocean tile on top, the one that makes you draw a card. I got an error popup, something about unexpected empty draw deck I think. After that the game is stuck:

- the actions section is asking me to select a space to place the Mangrove
- the tile I played it on has a blinking Mangrove icon:
![obraz](https://user-images.githubusercontent.com/50764073/156592045-d607c92e-d672-45ff-9251-a53acb70a53b.png)
- the log shows that Mangrove was played:
![obraz](https://user-images.githubusercontent.com/50764073/156594395-b2179514-f989-4cad-b2e6-1416e3194a9b.png)

Reloading the browser tab did not fix it.

**Comment by bafolts** [comment] 2022-03-03 15:28
Was this on terraforming-mars.herokuapp.com? If so do you have the game id?

**Comment by ilozen** [comment] 2022-03-03 15:30
Yes, here's the link, it's the first player:
[g8d0e746b9461](https://terraforming-mars.herokuapp.com/game?id=g8d0e746b9461)

**Comment by ilozen** [comment] 2022-03-05 12:32
I've returned to the game after a while and it resets to the state from before the Mangrove is played.
I tried to:

- play a card that causes you to draw a card => same result
- sell 1 card (to have something in the deck) and then play Mangrove on the same tile => same result

The next time it resets I'll try to end turn or sell cards and end turn, to see what happens then. But based on what I've seen so far it seems safe to say that it's an issue with card drawing in itself.

**Comment by ilozen** [comment] 2022-03-05 18:08
I've tried that and passing the turn displays error but if you do it again you can continue to next generation.
However, if i sell 8 cards (2-player game) I also get the error and on the next generation the card buying phase is skipped. So the cards I sold did not get shuffled to form a new deck. I double checked in the rule book and sold cards get discarded so they should end up in the same pile as not bought cards and be used when shuffing new deck.

**Comment by kberg** [comment] 2023-09-04 03:11
I've rewritten card discard piles, and unpurchased draft cards are most certainly discarded.

Also, when there are no more cards to deal, you actually deal an even number of cards per player, rather than blindly exhausting the deck. Huh.

**Comment by kberg** [comment] 2024-02-29 19:38
Duplicate of #5163

**Closed by kberg** 2024-02-29 19:38 UTC
