### ISSUE TITLE
Double Down not fully copying Colony Trade Hub.

### ISSUE THREAD

**Issue by 167kamon** [terraforming-mars/terraforming-mars#6364] opened 2024-01-14 02:21 UTC
Don't know if this is working as intended. Using Double Down to copy Colony Trade Hub doesn't double the "money gained from placing a colony" effect. Do passive effects not count as "Direct Effects" for the purposes of Double Down?
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s7bad50d8bc6",
  "color": "green",
  "step": 10,
  "version": "1ada85f",
  "builtAt": "Wed, 10 Jan 2024 03:12:28 GMT",
  "browser": "Firefox 121",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment] 2024-01-14 06:21
I believe, as you say, passive effects don't count as direct effects. If there's something that suggests otherwise, let me know.

In the meantime I'm going to close this since (I think) it's working as intended. If you have more information, feel free to just respond to this bug and I'll reopen it.

**Closed by kberg** 2024-01-14 06:22 UTC
