### ISSUE TITLE
Undo does not work anymore

### ISSUE THREAD

**Issue by Albinouze** [terraforming-mars/terraforming-mars#4619] opened 2022-07-04 13:31 UTC
Maybe it is only true for 2 players games but undo does not work since a few weeks. Before we had an error message when undo failed, now it looks like it worked but nothing changes.
thank you for the great work

**Comment by kberg** [comment] 2022-07-04 17:56
Yep, duplicate of #4505. I'm hoping to fix it soon. Thank you, sorry for the disruption.

**Closed by kberg** 2022-07-04 17:56 UTC
