### ISSUE TITLE
Undo not working Version: 39c09ef55

### ISSUE THREAD

**Issue by rogerta** [terraforming-mars/terraforming-mars#5259] opened 2023-01-23 21:58 UTC
I tried to undo the first of my two actions, which was to raise the temperature using 8 heat.  I got a message that the undo was performed but refreshing the page showed that it had not.  When I played my next action the next player became active.

I am running terraforming-mars on my own server, let me know what extra info I can provide like logs or whatnot.  I can also edit the `.env` file to increase logging in the future if that would help.

Info from gear icon:
```
URL: <redacted>
Player color: undefined
Step: undefined
Version: 39c09ef55, built at Wed, 11 Jan 2023 08:58:52 -0500
Browser: Chrome 108
```
This info was generated from the home page, i.e. not in the middle of game.

My terraforming-mars server is a full patched raspberry pi:
```
$ uname -a
Linux rpi4a 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux

$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by kberg** [comment] 2023-01-24 07:15
The stdout log would have been most helpful here. I can't reproduce it
without more details. I'm sorry.

I'll add that I'm trying to replace the Undo behavior with something
hopefully slightly better. So if it's OK with you, perhaps this isn't worth
spending any time on.

-Robert

**Comment by kberg** [comment] 2023-01-25 02:42
I'm closing this issue. Please feel free to reopen it if you have any questions.

**Closed by kberg** 2023-01-25 02:42 UTC
