### ISSUE TITLE
Enhancement: Add onsite link to make it easier to report bugs

### ISSUE THREAD

**Issue by nwai90** [terraforming-mars/terraforming-mars#1109] opened 2020-08-03 14:46 UTC
Suggestion to add a “Report a bug” link/icon somewhere unobtrusive so that players can raise issues directly.

For simplicity the link/icon could simply open Discord #general channel in a new tab.

**Comment by kberg** [comment] 2022-04-19 21:30
Closing this as a duplicate of #2760. Although the advanced version idea scares me because of the need for gh credentials.

**Closed by kberg** 2022-04-19 21:30 UTC
Labels: enhancement, good first issue
