### ISSUE TITLE
Wrong player name when production decreased

### ISSUE THREAD

**Issue by Engmostafam** [terraforming-mars/terraforming-mars#4572] opened 2022-06-18 17:40 UTC
It is supposed to say Green resource production decreased by Red

instead it says
🕑Red played Power Supply Consortium
🕑Red's energy production decreased by 1 stolen by Red

URL: https://terraforming-mars.herokuapp.com/spectator?id=s1ad0a370caac#cards
Player color: green
Step: 47
Version: 1f83bad, built at Wed, 15 Jun 2022 03:25:53 GMT
Browser: Firefox 101

**Comment by kberg** [comment] 2022-06-19 19:55
Thanks for the report. I just read the code and it looks correct. Are you certain that you lost production?

**Comment by Engmostafam** [comment] 2022-06-19 20:07
Interesting. It could be that red decreased her own production by mistake. I am not certain that my production was lost. Could be a false alarm. Sorry. Love the online version btw. 

For some reason though, the discord invitation and bug report links don’t seem to work for me. It says link invalid or I have no permission. 

Warm regards, 
Mostafa

**Comment by kberg** [comment] 2022-06-19 20:24
Which links are those?

**Comment by Engmostafam** [comment] 2022-06-19 21:15
From the report bug feature:https://discord.com/channels/737945098695999559


  &
From the home page:
https://discord.com/invite/VR8TbrD






    On Sunday, June 19, 2022, 09:24:14 PM GMT+1, Robert Konigsberg ***@***.***> wrote:  
 
 


Which links are those?

**Comment by kberg** [comment] 2022-06-29 04:50
I'm going to close this. It sounds like the issue isn't confirmed, and I fixed the discord links. Please let me know if you see it again.

**Closed by kberg** 2022-06-29 04:50 UTC
