### ISSUE TITLE
bug with eccentric sponsor

### ISSUE THREAD

**Issue by kaybauera** [terraforming-mars/terraforming-mars#5991] opened 2023-09-21 01:25 UTC
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s71788a8887b3",
  "color": "purple",
  "step": 97,
  "version": "3e89d4d",
  "builtAt": "Wed, 20 Sep 2023 03:41:39 GMT",
  "browser": "Chrome 116",
  "language": "en",
  "experimental_ui": false
}

When playing the prelude eccentric sponsor the discarded card does not leave hand and it is still playable.

**Comment by kberg** [comment] 2023-09-21 03:57
I read the game log. Excentric Sponsor played Water Import from Europa, which was then out of their hand. I don't see the bug.

I'm closing this issue. If there is new information, please add it; I'll still see it.

**Closed by kberg** 2023-09-21 03:57 UTC

**Comment by kaybauera** [comment] 2023-09-21 04:00
Sorry, I meant that focused organization didn't work as intended. I could get resource exchange and new cards dealt but the discarded card did not leave the hand and I could still play it.

Best,
Kaylyn Bauer, Ph.D
they/them
Postdoctoral Associate
Noah Palm Lab
Department of Immunobiology
Yale University
________________________________

**Comment by kberg** [comment] 2023-09-21 04:27
Gotcha. This is a duplicate of #5989 which I'm about to fix. Thanks for the report, either way!
