### ISSUE TITLE
How to keep up locales updated?

### ISSUE THREAD

**Issue by aloisdg** [terraforming-mars/terraforming-mars#5338] opened 2023-02-11 01:54 UTC
Hello,

First,

is there any will to use [weblate](https://weblate.org/en/) or an alternative? There are free solutions build exactly for this kind of problem. If so, I volunteer to look into it.

Meanwhile,

we can find the largest file with following script:

```bash
$> find . -name "log_messages.json" -type f -exec jq -r '[input_filename,length]|@tsv' {} +
./src/locales/ru/log_messages.json	28
./src/locales/de/log_messages.json	318
./src/locales/cn/log_messages.json	102
./src/locales/br/log_messages.json	175
./src/locales/it/log_messages.json	71
./src/locales/fr/log_messages.json	327
./src/locales/ko/log_messages.json	154
./src/locales/es/log_messages.json	93
./src/locales/pl/log_messages.json	229
```

then run the following node script `node updateLocale.js src/locales/de/log_messages.json ./src/locales/fr/log_messages.json`, with `updateLocale.js` being:

```js
const {promises: fs} = require("fs");

if (process.argv.length < 4) {
  console.log('Usage: node ' + process.argv[1] + ' <FILENAME> to fill <FILENAME> with.');
  process.exit(1);
}

const inputPath = process.argv[2];
const outputPath = process.argv[3];

(async () => {
  try {
    const inputFile = await fs.readFile(inputPath, 'utf-8');
    const outputFile = await fs.readFile(outputPath, 'utf-8');

    const inputData = JSON.parse(inputFile);
    const outputData = JSON.parse(outputFile);

    for (const key in inputData) {
      if (!outputData[key]) {
        outputData[key] = inputData[key];
      }
    }
    const content = JSON.stringify(outputData, null, 4);

    await fs.writeFile(outputPath, content, 'utf-8');
  } catch (e) {
    console.log('e', e);
  }
})()
```
In my case the output look like this:

![image](https://user-images.githubusercontent.com/3449303/218232485-0642b2ce-5c12-4194-b574-a819e8f4d71e.png)

Not sure if this will help, but it was useful to me at least...

So to come back to my question, how to keep up locals updated? What about Weblate? :smiling_face_with_tear: 

Cheers,

**Comment by kberg** [comment] 2023-02-11 06:35
If I understand correctly, Weblate provides a mechanism to store translations separate from the source control system itself, allowing people to make translations without having to deal with git. Clearly that's not all of it, but do tell me if that's the most important part.

It also looks as though there's nothing to do with regard to changing the application itself. But somehow we have to tell Weblate what needs to be translated. Is that where the translation strings get used?

Another note: did you know that if you show the browser console, it will print out the text that is not translated? I don't know if that can help.

**Comment by aloisdg** [comment] 2023-02-11 10:22
You get the most important part. Yes we have to share the translation keys. Then you can output [json files like today](https://docs.weblate.org/en/latest/formats.html#js-i18next).

For the note, no I was not aware of that. I will look into it.

**Comment by kberg** [comment] 2023-02-15 01:05
Weblate certainly looks interesting. I'd be interested in what you find out. Someone on Discord just asked about starting a Dutch translation so this is well timed. OK it's not that well timed, but you make a convincing proposal.

**Comment by kberg** [comment] 2023-02-25 21:09
Anything interesting yet?

**Comment by aloisdg** [comment] 2023-02-25 23:57
@kberg well weblate is free but the hosting is not. Alas I don't have a server (but I would love to take the time to learn how). A proprietary popular alternative is [Crowdin](https://crowdin.com/pricing#annual) (the hosting and the software is gratis. (well we are the product, you know the drill)).

**Comment by Heziode** [comment] 2023-05-06 21:46
The use of an l10n platform is already talked into #1360, and nothing seems changed since the discussion.
It is a shame, because it would allow more people to translate the application and cover a wider audience.
But it may not be the priority 🤷‍♂️

**Comment by kberg** [comment] 2024-02-07 18:29
Closing this as a duplicate of #1360. If there's any interest in taking action, please let me know. I don't care which bug it gets done under. ;D

**Closed by kberg** 2024-02-07 18:29 UTC
