### ISSUE TITLE
Obtaining Mega credits when placing greeneries

### ISSUE THREAD

**Issue by Abeloplus** [terraforming-mars/terraforming-mars#6146] opened 2023-10-26 07:38 UTC
When Pink player placed a greenery, some megacredits return to him. I'm unsure how to reproduce this bug because there were no card effects active that gave megacredits on placement.
https://terraforming-mars.herokuapp.com/the-end?id=sd4640dd27264

**Comment by kberg** [comment] 2023-10-26 11:35
Can you say a little more? Were you the pink player? How often did you
observe this? When was the last generation you saw it happen?

**Comment by Abeloplus** [comment] 2023-10-26 23:37
I was the pink player buy I can't say more about this than that I saw it happen like 3 times in the match (that I was aware about), this megacredits returned to me didn't appear in the log, so I don't exactly know how to reproduce the bug, if I see it happen again I will comment it here.

**Comment by Abeloplus** [comment] 2023-10-27 00:08
![image](https://github.com/terraforming-mars/terraforming-mars/assets/149048327/45a5b903-f6b2-4480-930a-88a0e5d5680c)
![image](https://github.com/terraforming-mars/terraforming-mars/assets/149048327/ec6765bf-4c53-432c-b001-7227be8bb564)
Here blue player used "MARS NOMADS" and he got 2 megacredits
![image](https://github.com/terraforming-mars/terraforming-mars/assets/149048327/7d2365cd-07ec-443d-ba75-2dcbf79711cf)

**Comment by kberg** [comment] 2023-10-27 15:11
Thanks for sending so much information! Unfortuanately, it's everything but the information I need. 

If it happens again, press the gear icon, select Report Bug, and copy/paste the data there into this bug.

**Comment by kberg** [comment] 2023-10-28 16:51
I am going to close this because there is not enough information to reproduce the issue. If you find this still happening, open another issue, or add a comment here.

**Closed by kberg** 2023-10-28 16:51 UTC

**Comment by Abeloplus** [comment] 2023-10-29 03:47
{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=se5489eb5a02a",
  "color": "red",
  "step": 6,
  "version": "144585a",
  "builtAt": "Sun, 29 Oct 2023 03:39:48 GMT",
  "browser": "Chrome 118",
  "language": "en",
  "experimental_ui": false
}
I just opened a solo game with a lot of initial TR, planted a bunch of greeneries, cities and oceans. I got 2 MC when I placed an ocean. Seems to only happen when there's a lot of tiles placed.

**Comment by kberg** [comment] 2023-10-29 04:11
A little more data will be helpful, please. Do you remember the M€ before
and after?

**Comment by kberg** [comment] 2023-10-29 04:12
You're not referring to the 2M€ bonus players get when placing a tile next to oceans, are you?

**Comment by Abeloplus** [comment] 2023-10-29 13:10
> You're not referring to the 2M€ bonus players get when placing a tile next to oceans, are you?

I just looked it up, I don't know how we didn't know that, I think my group and I have played like 20 games without knowing that😢, sorry for wasting your time.

**Comment by kberg** [comment] 2023-10-29 13:18
Fantastic! Keep learning, have fun.
