### ISSUE TITLE
Double down incomplete 

### ISSUE THREAD

**Issue by Tafareeeeel** [terraforming-mars/terraforming-mars#6638] opened 2024-04-26 15:08 UTC
My opponent played double down but didn't have the money to copy his prelude, so he received 15 mc and got to play project cards  before the other players played their respective preludes.

https://terraforming-mars.herokuapp.com/player?id=pe5fa762b76fd

**Comment by kberg** [comment] 2024-04-30 18:47
This sounds really bad, but nobody in this game played Double Down.

I'll close this. But if you have some new information I'll be happy to reopen it.

**Closed by kberg** 2024-04-30 18:47 UTC

**Comment by ryoku** [comment] 2024-05-02 10:47
@kberg I was having a look into this: actually it is reproducible. For me the issue is in class PreludesExpansion:

```
player.defer(() => {
      // This is deferred because it is possible for the parent card to
      // be moved from hand to play area. So, wait until this action finishes and
      // then follow up with cleanup.
      inplaceRemove(player.preludeCardsInHand, card);
      inplaceRemove(player.playedCards, card);
    }); 
```

Deferring DoubleDown removal from hand causes player turn not to finish.
