### ISSUE TITLE
When playing the merger prelude card, the corporation deck ran out of cards and was not reshuffled

### ISSUE THREAD

**Issue by leobarlach** [terraforming-mars/terraforming-mars#5178] opened 2022-12-10 00:03 UTC
URL: http://terraforming-mars.herokuapp.com/spectator?id=s7bed635ee9fa
Player color: yellow
Step: 16
Version: bc55fff, built at Fri, 02 Dec 2022 21:16:21 GMT
Browser: Chrome 108

When playing the merger prelude card, the corporation deck ran out of cards and was not reshuffled.

I couldn't pick a new corporation nor continue without picking. The game couldn't go on. 

Log said the corporation discard pile was reshuffled to form a new deck. But that didn't seem to work.

**Comment by kberg** [comment] 2022-12-18 22:44
Today is "make sure every open bug has a comment" day!

Yeah, Merger prelude + custom corporation lists is just not working well. It's not getting a very high priority right now.

**Comment by kberg** [comment] 2024-10-27 17:34
This is a duplicate of #5139 which has more detail, so I'm closing this one.

**Closed by kberg** 2024-10-27 17:34 UTC
Labels: bug
