### ISSUE TITLE
[Moon, PF] Heavy Duty Rovers bug

### ISSUE THREAD

**Issue by HenrikSteenbock** [terraforming-mars/terraforming-mars#5065] opened 2022-10-16 04:45 UTC
The green player had Odyssey to replay events. Lunar Mine Urbanization was re-played thanks to Odyssey so now there are 2 special tiles that count both as Mine and as Habitat. In total we now had 4 regular Mines and 2 special Mines. When Heavy Duty Rovers was played, the green player only got 16 MC for 4 Mines adjacent next to roads when really it is 5 Mines. See image for reference.

My best guess is that maybe something went wrong with Lunar Mine Urbanization being re-played i.e. it does a check for that special tile and adds 1 to the count of its present, as opposed to counting how often that special tile occurs and adding that number. Maybe there is just a straight up counting problem in Heavy Duty Rovers, though I use that card regularly and never noticed any issues.

For reference:
URL: https://terraforming-mars.herokuapp.com/spectator?id=sf6ea020f5478
Player color: orange
Step: 658 (described bug actually took place a few steps before that)
Version: 10e27a6, built at Sat, 15 Oct 2022 15:09:09 GMT
Browser: Firefox 105

![grafik](https://user-images.githubusercontent.com/44550180/196018405-883eb4cb-8c9d-4da3-966b-7bb71a017c40.png)

**Comment by kberg** [comment] 2022-10-16 05:36
Rules question: should Lunar Mine Urbanization be replayable if it is the
only mine the player has?

This comes back to the question in another bug about whether special tile
cards can be replayed.

**Comment by HenrikSteenbock** [comment] 2022-10-16 05:54
I don't think you should be able to play Lunar Mine Urbanization on top of an already urbanized Mine for the following reasons:

1) Thematically, it would make no sense.
2) Game-play-wise, I would argue that while the urbanized Mine is still a Mine, its's more than just that and, consequently, no longer a plain Main that you can place on top.

**Comment by kberg** [comment] 2022-10-16 15:35
So I've added a new automatic test that verifies it gains 20MC. I honestly don't know why it granted on 16. It doesn't quite make sense to me. It had nothing to do with Odyssey, though. I'm going to close this since I can't reproduce it, which means maybe I did fix it with some of the other code, but /shrug?

**Closed** 2022-10-16 15:45 UTC
