### ISSUE TITLE
Add to the log information about resources which was spent for a card 

### ISSUE THREAD

**Issue by Femirion** [terraforming-mars/terraforming-mars#6689] opened 2024-05-24 11:53 UTC
Hi, thank you for this web-version, I am happy to have play your game!

My proposal is add detail information about resources which was spent for a card. For example, if I have the Earth catapult and I play Space elevator and I pay 3 steel and 2 titan, I would like to see in the game chat: You played SPACE ELEVATOR (you spent: 13 MK, 3 steel, 2 titan, 2 MK discount)

**Comment by kberg** [comment] 2024-05-24 14:29
That's a great suggestion. The reason it hasn't been done is because I'm concerned about how much disk space it would take in our app. But I will think about it again.

**Comment by kberg** [comment] 2024-10-13 13:57
This is pretty much a duplicate of #1976 so I'm closing this as a duplicate.

**Closed by kberg** 2024-10-13 13:57 UTC
Labels: enhancement
