### ISSUE TITLE
Can't finish the game with last greenery tile

### ISSUE THREAD

**Issue by eth00** [terraforming-mars/terraforming-mars#6067] opened 2023-10-03 13:53 UTC
Please include:
1. A clear and concise description of the bug.
2. Clear steps to reproduce, and the expected behavior.
3. Any screenshots
4. Any information from  the Bug Report Dialog

We played the game for two, and my last action was placing a final greenery tile to the last free hex on the map. I got an error box with some Java exception text (sorry, I didn't take a screenshot then)
After pressing OK button on the error box and refreshing the page with ^R
 from my keyboard, the last tile shows a blinking greenery tile with my marker on it. There wasn't any free hex anymore, but the prompt was like
( )Place a greenery tile
( ) don't place anything

Any option from above didn't let me place a tile or finish the game

Screenshot: ![image](https://github.com/terraforming-mars/terraforming-mars/assets/4353313/a4338381-9051-4d72-a951-bc86c198fdd9)

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s496557792b51",
  "color": "blue",
  "step": 288,
  "version": "0caf3bf",
  "builtAt": "Tue, 03 Oct 2023 12:21:49 GMT",
  "browser": "Chrome 116",
  "language": "en",
  "experimental_ui": true
}

**Comment by kberg** [comment] 2023-10-07 04:10
Closing with the presumption that the issue is resolved. Please add comments if this is wrong.

**Closed by kberg** 2023-10-07 04:10 UTC
