### ISSUE TITLE
Visual issue with Deimos colony

### ISSUE THREAD

**Issue by Borbarad2** [terraforming-mars/terraforming-mars#6792] opened 2024-07-06 08:24 UTC
Visual issue with Deimos colony: The colony marker is offset to the colony track:
![grafik](https://github.com/terraforming-mars/terraforming-mars/assets/105346182/051b34bd-318a-43cb-a78d-f0f80b149350)

And the colony marker from the player is offset as well:
![grafik](https://github.com/terraforming-mars/terraforming-mars/assets/105346182/daf32c3e-b3ed-448b-ad06-0f46d57606b7)

{
  "url": "http://terraforming-mars.herokuapp.com/spectator?id=sac5c3cdce81e",
  "color": "green",
  "step": 196,
  "version": "e5e8573",
  "builtAt": "Thu, 04 Jul 2024 13:18:24 GMT",
  "browser": "Firefox 127",
  "language": "de",
  "experimental_ui": true
}

**Comment by kberg** [comment] 2024-07-09 01:15
Closing as a duplicate of #6796.

**Closed by kberg** 2024-07-09 01:15 UTC
