### ISSUE TITLE
Trying to draw from empty project deck with empty discard pile fails

### ISSUE THREAD

**Issue by Riidi** [terraforming-mars/terraforming-mars#6269] opened 2023-11-28 19:49 UTC
I was playing a solo game and wound up with all project cards either in my hand or in play, with a totally empty discard and draw pile. From that point on, selling and discarding cards did not refill a discard pile that could be reshuffled into a draw pile, and the play of some cards (such as Terraforming Ganymede) just outright gave an Error with input: Unexpected empty project deck

{
  "url": "https://terraforming-mars.herokuapp.com/spectator?id=s5cb766f01795#actions",
  "color": "red",
  "step": 701,
  "version": "2b312e6",
  "builtAt": "Tue, 28 Nov 2023 05:58:00 GMT",
  "browser": "Chrome 119",
  "language": "en",
  "experimental_ui": false
}

**Comment by kberg** [comment] 2024-01-21 18:53
How did you manage to do that in a solo game? Fascinating. I should have looked more closely when you first reported this.

**Comment by kberg** [comment] 2024-01-21 18:54
Also, this is a duplicate of #4772

**Comment by kberg** [comment] 2024-01-21 18:54
(I've closed this, but feel free to add comments.)

**Closed** 2024-01-21 18:54 UTC

**Comment by sanyassh** [comment] 2024-02-18 13:31
@kberg Hello! Is there any chance this issue will be fixed? I enjoy playing solo games with short deck of good cards, so I end up every game with empty deck and this error always annoys me.
