### ISSUE TITLE
In-game log update removes cards being looked at

### ISSUE THREAD

**Issue by Seth0326** [terraforming-mars/terraforming-mars#4455] opened 2022-05-16 01:24 UTC
During a game, when another player plays a card, I like to click on the card's name in the game log to see what it does. But if, while I'm looking at the card, the log updates because the player took another action, the card I'm looking at vanishes, and I have to click it again. Is there a way to keep it visible even if the log updates? Otherwise, if it's a fast game, it's really hard to keep track of what other people play unless I can recognize cards just by their titles.

**Comment by kberg** [comment] 2022-05-18 02:54
Thanks for the report. This is a duplicate of #4250

**Closed** 2022-05-18 02:54 UTC
