### ISSUE TITLE
[Enhancement] Add VP Progression chart (graph) as part of end game results

### ISSUE THREAD

**Issue by ctawa** [terraforming-mars/terraforming-mars#4275] opened 2022-04-03 01:26 UTC
Display a progression chart of attained VP (total) by player by the end of each generation. 

1. The start of the game, "Generation 0", store starting VP (20)
> Given that the game is at Generation 0" (start of game) 
 > When all the players have made their initial card selection
> Then each played/selected corporation (or player's name) is stored with its initial starting VP 

2. Gained or lost (negative) VP points are added to the previous generation's total for each subsequent generation
> Given I have an initial amount of VP
> When all players have passed the current generation
> Then gained (or lost) VP are reflected in my newly stored VP total for the current generation

3. Chart displayed with result at the end of the game
> Given that terraforming conditions have been met
> And all player's passed I have an initial amount of VP
> When the last players has placed any last potential greenery
> Then the chart with a per generation VP total is displayed with the end of game results.

- See attached image as a sample/idea of add-on

![TM_results-VP progression chart](https://user-images.githubusercontent.com/102814992/161316918-9f270b43-d54c-45a8-8f92-ab0b12f5dc35.png)

**Comment by kberg** [comment] 2022-04-03 02:35
Thanks! We're pretty well aware of the end-of-game graph. It's really just
a matter of somebody doing it.

**Comment by kberg** [comment] 2022-04-10 13:18
This is a duplicate of #3535.

**Closed by kberg** 2022-04-10 13:18 UTC
