### ISSUE TITLE
Energy market is converting wrongly

### ISSUE THREAD

**Issue by Belcarnen** [terraforming-mars/terraforming-mars#4942] opened 2022-09-15 05:45 UTC
Energy market card should create 1 energy for 2x money. It indeed asks to spend double the amount of money, but then converts 1:1.

Eg. if I ask for 3 energy it requires me to spend 6 money, but then adds 6 energy.

**Comment by kberg** [comment] 2022-09-15 05:51
Duplicate of #4930. This is fixed at head.

**Closed by kberg** 2022-09-15 05:51 UTC
